# Generated by Django 6.0.2 on 2026-02-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("SENSITY", "Sensity"), ("OTHER", "Other")],
                        default="SENSITY",
                        max_length=55,
                    ),
                ),
                ("token", models.CharField(max_length=555)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
