# Generated by Django 6.0.2 on 2026-02-12 10:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deepfake_detection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeepfakeTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "media_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("media_url", models.URLField(blank=True, null=True)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("report_ids", models.JSONField(blank=True, null=True)),
                ("response_full", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="created", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deepfake_detection.serviceprovider",
                    ),
                ),
            ],
        ),
    ]
