# Generated by Django 6.0.2 on 2026-02-11 08:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("api_key", models.CharField(max_length=100, unique=True)),
                ("public_key", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RequestNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_user_id", models.CharField(max_length=255)),
                ("decision", models.CharField(max_length=20)),
                ("reason", models.TextField()),
                ("device_hash", models.CharField(max_length=64)),
                ("sim_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bank"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("package_name", models.CharField(max_length=255)),
                ("certificate_hash_sha256", models.CharField(max_length=64)),
                ("encrypted_certificate", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bank"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_user_id", models.CharField(max_length=255)),
                ("device_fingerprint_hash", models.CharField(max_length=64)),
                ("sim_iccid_hash", models.CharField(max_length=64)),
                ("hardware_public_key", models.TextField()),
                ("hardware_key_id", models.CharField(max_length=255)),
                ("package_name", models.CharField(max_length=255)),
                ("certificate_hash_sha256", models.CharField(max_length=64)),
                ("play_integrity_verdict", models.CharField(max_length=100)),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("first_registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bank"
                    ),
                ),
            ],
        ),
    ]
